name: petminder_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ⭐ SYSTEM + FILE PICKER
  file_picker: ^8.0.0

  # ⭐ FIREBASE DEPENDENCIES
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  # UI LIBRARIES
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9

  # IMAGE PICKER (MOBILE)
  image_picker: ^1.0.7

  # DATE FORMAT PACKAGE
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
